//mocked data for now

import { CarType } from "../common/types/car.type";

export const cars: CarType[] = [
    // {
    //     id: 1,
    //     model: "Audi R8",
    //     manufacturingYear: 2023,
    //     mileage: 1000,
    //     price: 3.2,
    //     acceleration: 3.2,
    //     dealer: "Audi Sport Center",
    //     modelUrl: "models/audi_r8.glb",
    // },
    // {
    //     id: 2,
    //     model: "BMW M4",
    //     manufacturingYear: 2023,
    //     mileage: 5000,
    //     price: 1.8,
    //     acceleration: 3.8,
    //     dealer: "BMW M Performance",
    //     modelUrl: "models/bmw_m4_realistic_free.glb",
    // },
    {
        id: 3,
        model: "Corvette C7",
        manufacturingYear: 2019,
        mileage: 15000,
        price: 1.5,
        acceleration: 3.7,
        dealer: "Chevrolet Performance",
        modelUrl: "models/corvette_c7.glb",
    },
    // {
    //     id: 4,
    //     model: "Ford Mustang 1965",
    //     manufacturingYear: 1965,
    //     mileage: 175000,
    //     price: 1.2,
    //     acceleration: 2.0,
    //     dealer: "Chevrolet Washington DC",
    //     modelUrl: "models/corvette_c7.glb",
    // },
    // {
    //     id: 5,
    //     model: "Honda Civic Type R FL5",
    //     manufacturingYear: 2023,
    //     mileage: 2000,
    //     price: 0.9,
    //     acceleration: 5.4,
    //     dealer: "Honda Performance Center",
    //     modelUrl: "models/honda_civic_type_r_fl5.glb",
    // },
    {
        id: 6,
        model: "Maserati Ghibli Hybrid",
        manufacturingYear: 2022,
        mileage: 10000,
        price: 2.1,
        acceleration: 5.7,
        dealer: "Maserati Luxury Motors",
        modelUrl: "models/maserati_ghibli_hybrid.glb",
    },
];
