/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RBLXSupercars (https://sketchfab.com/RBLXSupercars)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2010-bmw-m3-gts-dfae8144a0164dafb159b14f7ba43645
Title: 2010 BMW M3 GTS
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bmw(props) {
  const carRef = useRef()
    const { nodes, materials } = useGLTF('raw-models/2010_bmw_m3_gts.glb')
    return (
      <group {...props} dispose={null} ref={carRef}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials['Mesheschassis0101Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['Mesheschassis0111Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials['Mesheschassis1Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials['Mesheslight0011Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials['Mesheslight0021Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials['Mesheslight1Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials['Meshesmisc0011Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials['Meshesmisc0021Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials['Meshesmisc0031Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials['Meshesmisc1Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['ExtL21Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials['Meshesremap0021Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials['Meshesrotor11Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials['Meshestread11Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials['Mesheswheel11Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['Meshesbadges0011Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Meshesbadges0021Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Meshesbadges1Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Meshescab0011Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Meshescab0021Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Meshescab1Mtl.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Mesheschassis0081Mtl.002']}
        />
      </group>
    )
  }
  
  useGLTF.preload('raw-models/2010_bmw_m3_gts.glb')