/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BugattiVeyron(props) {
  const { nodes, materials } = useGLTF('raw-models/2009_bugatti_veyron_16.4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10001.geometry}
        material={materials.Ro1Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11001.geometry}
        material={materials.Ti1Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2001.geometry}
        material={materials.Meshpart1Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3001.geometry}
        material={materials.Meshpart2Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4001.geometry}
        material={materials.Meshpart3Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5001.geometry}
        material={materials.Meshpart4Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6001.geometry}
        material={materials.Meshpart5Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7001.geometry}
        material={materials.Meshpart6Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8001.geometry}
        material={materials.Paint1Mtl}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9001.geometry}
        material={materials.Ri1Mtl}
      />
    </group>
  )
}

useGLTF.preload('raw-models/2009_bugatti_veyron_16.4.glb')